### ISSUE TITLE
Error when adding to Package.swift

### ISSUE THREAD

**Issue by kschins** [vapor-community/StripeKit#5]
Any idea why when I add this to my Package.swift file and run `vapor xcode -y,` I get the following error:

error: the package stripekit[https://github.com/vapor-community/stripekit.git] @ 1.0.0 contains incompatible dependencies:
    swift-nio-http-client[https://github.com/swift-server/swift-nio-http-client.git] @ master

Error: Could not generate Xcode project: error: the package stripekit[https://github.com/vapor-community/stripekit.git] @ 1.0.0 contains incompatible dependencies:
    swift-nio-http-client[https://github.com/swift-server/swift-nio-http-client.git] @ master

**Comment by Andrewangeta** [comment]
@kschins StripeKit will only work with Vapor 4 and Swift NIO 2.x checkout [StripeProvider](https://github.com/vapor-community/stripe-provider) and choose the `vapor-3` branch  instead.

**Comment by kschins** [comment]
Thank you! Everything works like a charm, I appreciate the feedback.
